<?php

declare(strict_types=1);

/*
 * CLI-only provisioner for the disposable local production-image smoke test.
 * It has no HTTP route and refuses every database namespace other than the
 * exact run-owned Compose project generated by run-production-smoke.ps1.
 */
if (PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}

require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../includes/authorization.php';
require_once __DIR__ . '/../includes/portfolio_scoped_data.php';
require_once __DIR__ . '/../includes/public_lifecycle.php';
require_once __DIR__ . '/../includes/public_url.php';
require_once __DIR__ . '/../includes/media_access.php';

const PRODUCTION_SMOKE_PREFIX = 'ather_production_smoke_';

function productionSmokeFail(string $message): never
{
    fwrite(STDERR, "Production smoke fixture refused: {$message}\n");
    exit(1);
}

function requireProductionSmokeEnvironment(): string
{
    $project = getenv('ATHERCAR_PRODUCTION_SMOKE_PROJECT');
    $database = getenv('DB_NAME');
    if (getenv('ATHERCAR_PRODUCTION_SMOKE') !== '1'
        || !is_string($project)
        || preg_match('/^ather_production_smoke_[a-f0-9]{24}$/', $project) !== 1
        || !is_string($database)
        || !hash_equals($project, $database)) {
        productionSmokeFail('the exact run-owned project and database namespace is required.');
    }
    if (getenv('APP_ENV') !== 'production' || getenv('ATHERCAR_TEST_MODE') !== false) {
        productionSmokeFail('the fixture only supports the production runtime with test mode disabled.');
    }
    if (getenv('ATHERCAR_STORAGE_ROOT') !== '/var/lib/ather-career/storage') {
        productionSmokeFail('the expected disposable private-storage root is required.');
    }

    return $project;
}

function requireProductionSmokeSlug(mixed $candidate): string
{
    $slug = is_string($candidate) ? $candidate : '';
    if (preg_match('/^production-smoke-[a-f0-9]{24}$/', $slug) !== 1) {
        productionSmokeFail('the exact synthetic Portfolio slug is required.');
    }

    return requirePublicSlug($slug);
}

/** @return array{portfolio_id: int, user_id: int, is_published: int} */
function productionSmokePortfolio(PDO $database, string $slug): array
{
    $statement = $database->prepare(
        'SELECT id, owner_user_id, is_published
         FROM portfolios
         WHERE public_slug = :slug
         LIMIT 1'
    );
    $statement->execute(['slug' => $slug]);
    $row = $statement->fetch(PDO::FETCH_ASSOC);
    if (!is_array($row) || (int) $row['id'] < 1 || (int) $row['owner_user_id'] < 1) {
        throw new RuntimeException('Synthetic Portfolio is unavailable.');
    }

    return [
        'portfolio_id' => (int) $row['id'],
        'user_id' => (int) $row['owner_user_id'],
        'is_published' => (int) $row['is_published'],
    ];
}

function productionSmokeContext(array $portfolio): AuthorizedPortfolioContext
{
    return AuthorizedPortfolioContext::fromValidatedOwnership(
        AuthenticatedUserContext::fromValidatedUser($portfolio['user_id']),
        $portfolio['portfolio_id'],
    );
}

function productionSmokeCreatePng(string $path, int $red, int $green, int $blue): void
{
    $image = imagecreatetruecolor(96, 64);
    if ($image === false) {
        throw new RuntimeException('Synthetic image allocation failed.');
    }
    imagefill($image, 0, 0, imagecolorallocate($image, $red, $green, $blue));
    if (!imagepng($image, $path)) {
        imagedestroy($image);
        throw new RuntimeException('Synthetic image creation failed.');
    }
    imagedestroy($image);
}

/** @return list<string> */
function productionSmokeExpectedMigrations(): array
{
    $expected = [];
    foreach (glob(__DIR__ . '/../database/migrations/[0-9][0-9][0-9]_*.sql') ?: [] as $path) {
        if (preg_match('/\/([0-9]{3})_([a-z0-9][a-z0-9_-]*)\.sql$/', str_replace('\\', '/', $path), $matches) !== 1) {
            throw new RuntimeException('The repository migration manifest is malformed.');
        }
        $expected[] = $matches[1] . '_' . $matches[2];
    }
    sort($expected, SORT_STRING);

    return $expected;
}

function productionSmokeAssertSchema(PDO $database): void
{
    $ledger = $database->query('SELECT CONCAT(version, "_", name) FROM schema_migrations ORDER BY version')->fetchAll(PDO::FETCH_COLUMN);
    if ($ledger !== productionSmokeExpectedMigrations()) {
        throw new RuntimeException('The migration ledger does not exactly match the repository migration manifest.');
    }

    $required = [
        'portfolios' => ['public_slug', 'is_published', 'published_at'],
        'personal_info' => ['profile_image_path', 'public_contact_visible'],
        'projects' => ['image_path', 'technologies'],
        'messages' => ['recipient_portfolio_id'],
        'experiences' => ['portfolio_id', 'experience_type'],
    ];
    $statement = $database->prepare(
        'SELECT COUNT(*)
         FROM information_schema.columns
         WHERE table_schema = DATABASE() AND table_name = :table AND column_name = :column'
    );
    foreach ($required as $table => $columns) {
        foreach ($columns as $column) {
            $statement->execute(['table' => $table, 'column' => $column]);
            if ((int) $statement->fetchColumn() !== 1) {
                throw new RuntimeException('A required production schema field is missing.');
            }
        }
    }
}

/** @return array{portfolio_id: int, project_id: int} */
function productionSmokeSeed(PDO $database, string $slug): array
{
    $existing = $database->prepare('SELECT COUNT(*) FROM portfolios WHERE public_slug = :slug');
    $existing->execute(['slug' => $slug]);
    if ((int) $existing->fetchColumn() !== 0) {
        throw new RuntimeException('The run-owned slug already exists.');
    }

    $insertUser = $database->prepare(
        'INSERT INTO users (oidc_issuer, oidc_subject, account_status, authz_version)
         VALUES (:issuer, :subject, "active", 1)'
    );
    $insertUser->execute([
        'issuer' => 'https://owner-smoke.invalid/',
        'subject' => 'owner-' . substr($slug, -24),
    ]);
    $userId = (int) $database->lastInsertId();
    $insertPortfolio = $database->prepare('INSERT INTO portfolios (owner_user_id) VALUES (:owner_user_id)');
    $insertPortfolio->execute(['owner_user_id' => $userId]);
    $portfolioId = (int) $database->lastInsertId();
    $context = AuthorizedPortfolioContext::fromValidatedOwnership(
        AuthenticatedUserContext::fromValidatedUser($userId),
        $portfolioId,
    );

    $profileSource = tempnam(sys_get_temp_dir(), 'ather-smoke-profile-');
    $projectSource = tempnam(sys_get_temp_dir(), 'ather-smoke-project-');
    if ($profileSource === false || $projectSource === false) {
        throw new RuntimeException('Synthetic media staging is unavailable.');
    }

    try {
        productionSmokeCreatePng($profileSource, 34, 110, 180);
        productionSmokeCreatePng($projectSource, 80, 150, 94);
        $profileImage = copyFileToPrivateMedia($profileSource, $portfolioId, 'profile_original', 'smoke-profile.png');
        $projectImage = copyFileToPrivateMedia($projectSource, $portfolioId, 'projects', 'smoke-project.png');
        if ($profileImage === null || $projectImage === null
            || generateProfilePresentationImage($profileImage, $portfolioId) === null
            || generateProjectPresentationImage($projectImage, $portfolioId) === null) {
            throw new RuntimeException('Synthetic media normalization failed.');
        }
    } finally {
        @unlink($profileSource);
        @unlink($projectSource);
    }

    createAuthorizedPersonalInfo($database, $context, [
        'full_name' => 'Production Smoke Owner',
        'professional_title' => 'Synthetic Production Engineer',
        'hero_headline' => 'Synthetic Portfolio used only for local production smoke testing.',
        'email' => 'owner@portfolio-smoke.invalid',
        'phone_primary' => '+962 700000000',
        'phone_secondary' => '',
        'location' => 'Synthetic City',
        'about_me' => 'Synthetic content only.',
        'work_description' => 'Synthetic production readiness validation.',
        'linkedin_url' => 'https://profile-smoke.invalid/linkedin',
        'github_url' => 'https://profile-smoke.invalid/github',
        'instagram_url' => '',
        'facebook_url' => '',
        'website_url' => '',
        'profile_image_path' => $profileImage,
        'public_contact_visible' => true,
    ]);
    createAuthorizedSkill($database, $context, 'Synthetic Reliability');
    createAuthorizedSkill($database, $context, 'Production Validation');
    $projectId = createAuthorizedProject(
        $database,
        $context,
        'Smoke Media Project',
        'Synthetic',
        'Synthetic project with private media.',
        'https://project-smoke.invalid/media',
        $projectImage,
        ['PHP', 'MySQL'],
    );
    createAuthorizedProject(
        $database,
        $context,
        'Smoke Text Project',
        'Synthetic',
        'Synthetic project without media.',
        'https://project-smoke.invalid/text',
        null,
        ['Apache'],
    );
    createAuthorizedExperience($database, $context, [
        'experience_type' => 'employment',
        'role_title' => 'Synthetic Production Engineer',
        'organization' => 'Smoke Validation',
        'location' => 'Synthetic City',
        'start_month' => '2024-01',
        'end_month' => '2024-12',
        'is_current' => false,
        'description' => 'Synthetic experience used by the smoke test.',
    ]);

    setOwnedPublicSlug($database, $context, $slug);
    publishOwnedPortfolio($database, $context);

    return ['portfolio_id' => $portfolioId, 'project_id' => $projectId];
}

function productionSmokeMessageCount(PDO $database, int $portfolioId): int
{
    $statement = $database->prepare('SELECT COUNT(*) FROM messages WHERE recipient_portfolio_id = :portfolio_id');
    $statement->execute(['portfolio_id' => $portfolioId]);

    return (int) $statement->fetchColumn();
}

/** @return list<string> */
function productionSmokeExpectedMigrationsThrough(string $version): array
{
    return array_values(array_filter(
        productionSmokeExpectedMigrations(),
        static fn (string $migration): bool => strcmp(substr($migration, 0, 3), $version) <= 0,
    ));
}

function productionSmokeAssertLedgerThrough(PDO $database, string $version): void
{
    $ledger = $database->query('SELECT CONCAT(version, "_", name) FROM schema_migrations ORDER BY version')->fetchAll(PDO::FETCH_COLUMN);
    if ($ledger !== productionSmokeExpectedMigrationsThrough($version)) {
        throw new RuntimeException('The migration ledger is not in the required pre-upgrade state.');
    }
}

/** @return array{user_id: int, portfolio_id: int, project_id: int} */
function productionSmokeSeedUpgradeState(PDO $database, string $slug): array
{
    productionSmokeAssertLedgerThrough($database, '008');

    $subject = getenv('PRESERVED_V1_OIDC_SUBJECT');
    if (!is_string($subject) || $subject === '') {
        throw new RuntimeException('The explicit preserved-owner subject is unavailable.');
    }
    $userStatement = $database->prepare(
        'SELECT id
         FROM users
         WHERE oidc_subject = :subject AND account_status = "active"
         LIMIT 1'
    );
    $userStatement->execute(['subject' => $subject]);
    $userId = (int) $userStatement->fetchColumn();
    if ($userId < 1 || (int) $database->query('SELECT COUNT(*) FROM users')->fetchColumn() !== 1) {
        throw new RuntimeException('The isolated pre-upgrade Owner is not uniquely established.');
    }

    $portfolioStatement = $database->prepare('SELECT id FROM portfolios WHERE owner_user_id = :user_id LIMIT 1');
    $portfolioStatement->execute(['user_id' => $userId]);
    $portfolioId = (int) $portfolioStatement->fetchColumn();
    if ($portfolioId < 1 || (int) $database->query('SELECT COUNT(*) FROM portfolios')->fetchColumn() !== 1) {
        throw new RuntimeException('The isolated pre-upgrade Portfolio is not uniquely established.');
    }
    $existingSlug = $database->prepare('SELECT COUNT(*) FROM portfolios WHERE public_slug = :slug');
    $existingSlug->execute(['slug' => $slug]);
    if ((int) $existingSlug->fetchColumn() !== 0) {
        throw new RuntimeException('The run-owned upgrade slug already exists.');
    }

    $profileSource = tempnam(sys_get_temp_dir(), 'ather-upgrade-profile-');
    $projectSource = tempnam(sys_get_temp_dir(), 'ather-upgrade-project-');
    if ($profileSource === false || $projectSource === false) {
        throw new RuntimeException('Synthetic upgrade media staging is unavailable.');
    }
    try {
        productionSmokeCreatePng($profileSource, 114, 86, 170);
        productionSmokeCreatePng($projectSource, 54, 136, 112);
        $profileImage = copyFileToPrivateMedia($profileSource, $portfolioId, 'profile_original', 'upgrade-profile.png');
        $projectImage = copyFileToPrivateMedia($projectSource, $portfolioId, 'projects', 'upgrade-project.png');
        if ($profileImage === null || $projectImage === null
            || generateProfilePresentationImage($profileImage, $portfolioId) === null
            || generateProjectPresentationImage($projectImage, $portfolioId) === null) {
            throw new RuntimeException('Synthetic upgrade media normalization failed.');
        }
    } finally {
        @unlink($profileSource);
        @unlink($projectSource);
    }

    $insertProfile = $database->prepare(
        'INSERT INTO personal_info (
            portfolio_id, full_name, professional_title, hero_headline, email,
            phone_primary, phone_secondary, location, about_me, work_description,
            linkedin_url, github_url, instagram_url, facebook_url, website_url,
            profile_image_path
        ) VALUES (
            :portfolio_id, :full_name, :professional_title, :hero_headline, :email,
            :phone_primary, :phone_secondary, :location, :about_me, :work_description,
            :linkedin_url, :github_url, :instagram_url, :facebook_url, :website_url,
            :profile_image_path
        )'
    );
    $insertProfile->execute([
        'portfolio_id' => $portfolioId,
        'full_name' => 'Synthetic Upgrade Owner',
        'professional_title' => 'Synthetic Existing Data Engineer',
        'hero_headline' => 'Synthetic state retained across the Production upgrade rehearsal.',
        'email' => 'owner-upgrade@portfolio-smoke.invalid',
        'phone_primary' => '+962 711111111',
        'phone_secondary' => '',
        'location' => 'Synthetic Upgrade City',
        'about_me' => 'Synthetic existing data only.',
        'work_description' => 'Synthetic production upgrade validation.',
        'linkedin_url' => 'https://upgrade-smoke.invalid/linkedin',
        'github_url' => 'https://upgrade-smoke.invalid/github',
        'instagram_url' => '',
        'facebook_url' => '',
        'website_url' => '',
        'profile_image_path' => $profileImage,
    ]);
    $insertSkill = $database->prepare('INSERT INTO skills (portfolio_id, skill_name) VALUES (:portfolio_id, :skill_name)');
    foreach (['Synthetic Upgrade Safety', 'Synthetic Existing State'] as $skill) {
        $insertSkill->execute(['portfolio_id' => $portfolioId, 'skill_name' => $skill]);
    }
    $insertProject = $database->prepare(
        'INSERT INTO projects (portfolio_id, title, category, description, github_url, image_path, technologies)
         VALUES (:portfolio_id, :title, :category, :description, :github_url, :image_path, :technologies)'
    );
    $insertProject->execute([
        'portfolio_id' => $portfolioId,
        'title' => 'Synthetic Existing Upgrade Project',
        'category' => 'Synthetic',
        'description' => 'Synthetic project retained across startup migration.',
        'github_url' => 'https://upgrade-smoke.invalid/project',
        'image_path' => $projectImage,
        'technologies' => json_encode(['PHP', 'MySQL'], JSON_THROW_ON_ERROR),
    ]);
    $projectId = (int) $database->lastInsertId();
    $insertExperience = $database->prepare(
        'INSERT INTO experiences (
            portfolio_id, experience_type, role_title, organization, location,
            start_month, end_month, is_current, description
        ) VALUES (
            :portfolio_id, :experience_type, :role_title, :organization, :location,
            :start_month, :end_month, :is_current, :description
        )'
    );
    $insertExperience->execute([
        'portfolio_id' => $portfolioId,
        'experience_type' => 'employment',
        'role_title' => 'Synthetic Existing Engineer',
        'organization' => 'Synthetic Upgrade Validation',
        'location' => 'Synthetic Upgrade City',
        'start_month' => '2023-01',
        'end_month' => '2023-12',
        'is_current' => 0,
        'description' => 'Synthetic Experience retained across the Production upgrade.',
    ]);
    $insertMessage = $database->prepare(
        'INSERT INTO messages (name, email, message, recipient_portfolio_id)
         VALUES (:name, :email, :message, :portfolio_id)'
    );
    $insertMessage->execute([
        'name' => 'Synthetic Existing Sender',
        'email' => 'sender-upgrade@portfolio-smoke.invalid',
        'message' => 'Synthetic existing contact payload retained without inspection.',
        'portfolio_id' => $portfolioId,
    ]);
    $publish = $database->prepare(
        'UPDATE portfolios
         SET public_slug = :slug, is_published = 1, published_at = CURRENT_TIMESTAMP
         WHERE id = :portfolio_id'
    );
    $publish->execute(['slug' => $slug, 'portfolio_id' => $portfolioId]);
    if ($publish->rowCount() !== 1) {
        throw new RuntimeException('The synthetic pre-upgrade publication state could not be established.');
    }

    return ['user_id' => $userId, 'portfolio_id' => $portfolioId, 'project_id' => $projectId];
}

/** @param list<array<string, mixed>> $rows */
function productionSmokeRowsFingerprint(array $rows): string
{
    $hash = hash_init('sha256');
    foreach ($rows as $row) {
        foreach ($row as $value) {
            hash_update($hash, $value === null ? "\\0" : (string) $value);
            hash_update($hash, "\\x1f");
        }
        hash_update($hash, "\\x1e");
    }

    return hash_final($hash);
}

function productionSmokeQueryFingerprint(PDO $database, string $query, array $parameters = []): string
{
    $statement = $database->prepare($query);
    $statement->execute($parameters);

    return productionSmokeRowsFingerprint($statement->fetchAll(PDO::FETCH_ASSOC));
}

/** @return array{count: int, fingerprint: string} */
function productionSmokePrivateMediaFingerprint(): array
{
    $root = getenv('ATHERCAR_STORAGE_ROOT');
    if (!is_string($root) || $root === '' || !is_dir($root)) {
        throw new RuntimeException('The isolated private-media root is unavailable.');
    }
    $mediaRoot = $root . DIRECTORY_SEPARATOR . 'portfolios';
    if (!is_dir($mediaRoot)) {
        return ['count' => 0, 'fingerprint' => hash('sha256', '')];
    }
    $files = [];
    foreach (new RecursiveIteratorIterator(new RecursiveDirectoryIterator($mediaRoot, FilesystemIterator::SKIP_DOTS)) as $file) {
        if (!$file instanceof SplFileInfo || !$file->isFile()) {
            continue;
        }
        $pathname = $file->getPathname();
        $digest = hash_file('sha256', $pathname);
        if ($digest === false) {
            throw new RuntimeException('A synthetic private-media fixture could not be fingerprinted.');
        }
        $files[] = substr(str_replace('\\', '/', $pathname), strlen(str_replace('\\', '/', $mediaRoot)) + 1) . "\\x1f" . $digest;
    }
    sort($files, SORT_STRING);

    return ['count' => count($files), 'fingerprint' => hash('sha256', implode("\\x1e", $files))];
}

/** @return array<string, int|string> */
function productionSmokeUpgradeFingerprint(PDO $database, string $slug): array
{
    $portfolio = productionSmokePortfolio($database, $slug);
    $portfolioId = $portfolio['portfolio_id'];
    $userId = $portfolio['user_id'];
    $media = productionSmokePrivateMediaFingerprint();
    $fingerprints = [
        'owner' => productionSmokeQueryFingerprint($database, 'SELECT id, oidc_issuer, oidc_subject, account_status, authz_version FROM users WHERE id = :id', ['id' => $userId]),
        'portfolio' => productionSmokeQueryFingerprint($database, 'SELECT id, owner_user_id, public_slug, is_published, published_at FROM portfolios WHERE id = :id', ['id' => $portfolioId]),
        'profile' => productionSmokeQueryFingerprint($database, 'SELECT id, portfolio_id, full_name, professional_title, hero_headline, email, phone_primary, phone_secondary, location, about_me, work_description, linkedin_url, github_url, instagram_url, facebook_url, website_url, profile_image_path, updated_at FROM personal_info WHERE portfolio_id = :id', ['id' => $portfolioId]),
        'skills' => productionSmokeQueryFingerprint($database, 'SELECT id, portfolio_id, skill_name, created_at FROM skills WHERE portfolio_id = :id ORDER BY id', ['id' => $portfolioId]),
        'projects' => productionSmokeQueryFingerprint($database, 'SELECT id, portfolio_id, title, category, description, github_url, image_path, technologies, created_at FROM projects WHERE portfolio_id = :id ORDER BY id', ['id' => $portfolioId]),
        'experiences' => productionSmokeQueryFingerprint($database, 'SELECT id, portfolio_id, experience_type, role_title, organization, location, start_month, end_month, is_current, description, created_at, updated_at FROM experiences WHERE portfolio_id = :id ORDER BY id', ['id' => $portfolioId]),
        // The message payload is deliberately not selected or fingerprinted.
        'messages' => productionSmokeQueryFingerprint($database, 'SELECT id, recipient_portfolio_id, created_at FROM messages WHERE recipient_portfolio_id = :id ORDER BY id', ['id' => $portfolioId]),
        'media_references' => productionSmokeQueryFingerprint($database, 'SELECT "profile" AS media_type, profile_image_path AS path FROM personal_info WHERE portfolio_id = ? UNION ALL SELECT "project" AS media_type, image_path AS path FROM projects WHERE portfolio_id = ? AND image_path IS NOT NULL ORDER BY media_type, path', [$portfolioId, $portfolioId]),
    ];
    $counts = [];
    foreach ([
        'users' => 'SELECT COUNT(*) FROM users',
        'portfolios' => 'SELECT COUNT(*) FROM portfolios',
        'profiles' => 'SELECT COUNT(*) FROM personal_info WHERE portfolio_id = :id',
        'skills' => 'SELECT COUNT(*) FROM skills WHERE portfolio_id = :id',
        'projects' => 'SELECT COUNT(*) FROM projects WHERE portfolio_id = :id',
        'experiences' => 'SELECT COUNT(*) FROM experiences WHERE portfolio_id = :id',
        'messages' => 'SELECT COUNT(*) FROM messages WHERE recipient_portfolio_id = :id',
        'media_references' => 'SELECT COUNT(*) FROM personal_info WHERE portfolio_id = ? AND profile_image_path IS NOT NULL UNION ALL SELECT COUNT(*) FROM projects WHERE portfolio_id = ? AND image_path IS NOT NULL',
    ] as $name => $query) {
        $statement = $database->prepare($query);
        $statement->execute(
            str_contains($query, ':id') ? ['id' => $portfolioId]
                : (str_contains($query, '?') ? [$portfolioId, $portfolioId] : []),
        );
        $values = $statement->fetchAll(PDO::FETCH_COLUMN);
        $counts[$name] = array_sum(array_map('intval', $values));
    }

    return [
        'user_id' => $userId,
        'portfolio_id' => $portfolioId,
        'is_published' => $portfolio['is_published'],
        ...$counts,
        'media_files' => $media['count'],
        'data_fingerprint' => hash('sha256', json_encode($fingerprints, JSON_THROW_ON_ERROR)),
        'media_fingerprint' => $media['fingerprint'],
        'owner_fingerprint' => $fingerprints['owner'],
        'ownership_fingerprint' => $fingerprints['portfolio'],
    ];
}

try {
    requireProductionSmokeEnvironment();
    $action = $argv[1] ?? '';
    $slug = requireProductionSmokeSlug($argv[2] ?? null);
    $database = getDatabaseConnection();

    if ($action === 'assert-schema') {
        productionSmokeAssertSchema($database);
        echo "{\"ok\":true,\"action\":\"assert-schema\"}\n";
        exit;
    }

    if ($action === 'seed') {
        $fixture = productionSmokeSeed($database, $slug);
        $portfolio = productionSmokePortfolio($database, $slug);
        if ($portfolio['is_published'] !== 1 || productionSmokeMessageCount($database, $fixture['portfolio_id']) !== 0) {
            throw new RuntimeException('Synthetic fixture did not start in the required publication state.');
        }
        $publicContext = resolvePublicReadContext($database, $slug);
        echo json_encode([
            'ok' => true,
            'action' => 'seed',
            ...$fixture,
            'profile_media_ready' => $publicContext !== null && publicMediaDescriptor($database, $publicContext, 'profile', null) !== null,
            'project_media_ready' => $publicContext !== null && publicMediaDescriptor($database, $publicContext, 'project', $fixture['project_id']) !== null,
        ], JSON_THROW_ON_ERROR) . "\n";
        exit;
    }

    if ($action === 'upgrade-seed') {
        $fixture = productionSmokeSeedUpgradeState($database, $slug);
        $fingerprint = productionSmokeUpgradeFingerprint($database, $slug);
        if ($fingerprint['is_published'] !== 1
            || $fingerprint['users'] !== 1
            || $fingerprint['portfolios'] !== 1
            || $fingerprint['profiles'] !== 1
            || $fingerprint['projects'] < 2
            || $fingerprint['experiences'] !== 1
            || $fingerprint['messages'] !== 1
            || $fingerprint['media_references'] < 2
            || $fingerprint['media_files'] < 2) {
            throw new RuntimeException('The synthetic pre-upgrade fixture is incomplete.');
        }
        echo json_encode([
            'ok' => true,
            'action' => 'upgrade-seed',
            ...$fixture,
            ...$fingerprint,
        ], JSON_THROW_ON_ERROR) . "\n";
        exit;
    }

    if ($action === 'upgrade-fingerprint') {
        echo json_encode([
            'ok' => true,
            'action' => 'upgrade-fingerprint',
            ...productionSmokeUpgradeFingerprint($database, $slug),
        ], JSON_THROW_ON_ERROR) . "\n";
        exit;
    }

    $portfolio = productionSmokePortfolio($database, $slug);
    if ($action === 'message-count') {
        echo json_encode(['ok' => true, 'count' => productionSmokeMessageCount($database, $portfolio['portfolio_id'])], JSON_THROW_ON_ERROR) . "\n";
        exit;
    }
    if ($action === 'assert-canonical-url') {
        $expected = 'https://portfolio-smoke.invalid/p/' . $slug;
        if (!hash_equals($expected, publicPortfolioUrl($slug))) {
            throw new RuntimeException('The canonical public URL does not use the configured HTTPS origin.');
        }
        echo "{\"ok\":true,\"action\":\"assert-canonical-url\"}\n";
        exit;
    }

    $context = productionSmokeContext($portfolio);
    if ($action === 'unpublish') {
        unpublishOwnedPortfolio($database, $context);
    } elseif ($action === 'republish') {
        publishOwnedPortfolio($database, $context);
    } elseif ($action !== 'state') {
        productionSmokeFail('an allowed action is required.');
    }

    $state = productionSmokePortfolio($database, $slug);
    echo json_encode([
        'ok' => true,
        'action' => $action,
        'portfolio_id' => $state['portfolio_id'],
        'is_published' => $state['is_published'],
        'message_count' => productionSmokeMessageCount($database, $state['portfolio_id']),
    ], JSON_THROW_ON_ERROR) . "\n";
} catch (Throwable $exception) {
    fwrite(STDERR, "Production smoke fixture failed: " . $exception->getMessage() . "\n");
    exit(1);
}
