<a class="skip-link admin-skip-link" href="#main-content">Skip to main content</a>
<aside class="admin-sidebar">
    <a class="admin-brand" href="admin.php"><span class="brand-mark">P</span><span>Portfolio Admin</span></a>
    <nav aria-label="Admin navigation">
        <span class="nav-group-label">Workspace</span>
        <a class="<?php echo $activePage === 'dashboard' ? 'active' : ''; ?>" href="admin.php" <?php echo $activePage === 'dashboard' ? 'aria-current="page"' : ''; ?>><span class="nav-icon"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><rect x="3" y="3" width="7" height="7" rx="1"></rect><rect x="14" y="3" width="7" height="7" rx="1"></rect><rect x="3" y="14" width="7" height="7" rx="1"></rect><rect x="14" y="14" width="7" height="7" rx="1"></rect></svg></span> Dashboard</a>
        <a class="<?php echo $activePage === 'personal_info' ? 'active' : ''; ?>" href="personal_info.php" <?php echo $activePage === 'personal_info' ? 'aria-current="page"' : ''; ?>><span class="nav-icon"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><circle cx="12" cy="8" r="3"></circle><path d="M5 21c.7-3.6 3.2-5.5 7-5.5s6.3 1.9 7 5.5"></path><path d="M4 3h16v18H4z"></path></svg></span> Personal info</a>
        <span class="nav-group-label">Content</span>
        <a class="<?php echo $activePage === 'projects' ? 'active' : ''; ?>" href="projects.php" <?php echo $activePage === 'projects' ? 'aria-current="page"' : ''; ?>><span class="nav-icon"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M3 7a2 2 0 0 1 2-2h5l2 2h7a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><path d="M3 9h18"></path></svg></span> Projects</a>
        <a class="<?php echo $activePage === 'messages' ? 'active' : ''; ?>" href="messages.php" <?php echo $activePage === 'messages' ? 'aria-current="page"' : ''; ?>><span class="nav-icon"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><rect x="3" y="5" width="18" height="14" rx="2"></rect><path d="m3 7 9 6 9-6"></path></svg></span> Messages</a>
    </nav>
    <div class="sidebar-footer"><a href="index.php" target="_blank" rel="noopener"><span class="nav-icon"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M14 3h7v7"></path><path d="m21 3-9 9"></path><path d="M19 14v5a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h5"></path></svg></span>Preview Portfolio</a><form class="sidebar-logout-form" method="POST" action="logout.php"><input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars(getCsrfToken(), ENT_QUOTES, 'UTF-8'); ?>"><button class="sidebar-logout-button" type="submit"><span class="nav-icon"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M10 17l5-5-5-5"></path><path d="M15 12H3"></path><path d="M21 3v18"></path></svg></span>Logout</button></form></div>
</aside>
