<?php

declare(strict_types=1);

/** Approved Arabic copy; English translation follows the same product structure. */
function landingCopy(string $key, string $locale): string
{
    static $catalog = [
        'brand' => ['ar' => 'أثر · Ather', 'en' => 'Ather · أثر'],
        'nav_why' => ['ar' => 'لماذا أثر؟', 'en' => 'Why Ather?'],
        'nav_how' => ['ar' => 'كيف تعمل؟', 'en' => 'How it works'],
        'nav_stories' => ['ar' => 'قصص المشاريع', 'en' => 'Project stories'],
        'sign_in' => ['ar' => 'تسجيل الدخول', 'en' => 'Sign in'],
        'start' => ['ar' => 'ابدأ بناء أثرك', 'en' => 'Start building your impact'],
        'hero_eyebrow' => ['ar' => 'هويتك المهنية أبعد من قائمة مهارات', 'en' => 'Your professional identity is more than a list of skills'],
        'hero_heading' => ['ar' => 'لا تعرض مشروعك فقط.', 'en' => 'Don\'t just show your project.'],
        'hero_impact' => ['ar' => 'أظهر الأثر الذي صنعته.', 'en' => 'Show the impact you made.'],
        'hero_lead' => ['ar' => 'حوّل مشاريعك وتجاربك إلى قصة مهنية موثقة تشرح المشكلة، دورك الحقيقي، والنتيجة التي وصلت إليها—حتى لا يضيع ما تعلمته مع الوقت.', 'en' => 'Turn your projects and experiences into a documented professional story that explains the problem, your real role, and the result—so what you learned is never lost over time.'],
        'explore' => ['ar' => 'اكتشف كيف تبني أثرك', 'en' => 'Explore how to build your impact'],
        'see_how' => ['ar' => 'شاهد كيف تعمل', 'en' => 'See how it works'],
        'beta' => ['ar' => 'انطلاقة تجريبية من الأردن · مجانية في المرحلة الأولى', 'en' => 'A pilot starting in Jordan · Free in the first stage'],
        'example_name' => ['ar' => 'محمد · مهندس ذكاء اصطناعي', 'en' => 'Mohammad · AI engineer'],
        'example_role' => ['ar' => 'أبني حلولًا تجمع التقنية مع احتياجات الناس', 'en' => 'I build solutions that connect technology with people\'s needs'],
        'careerfit' => ['ar' => 'CareerFit AI', 'en' => 'CareerFit AI'],
        'example_type' => ['ar' => 'منصة ذكاء مهني · مشروع محلي', 'en' => 'Career intelligence platform · Local project'],
        'example_badge' => ['ar' => 'أدلة مكتملة', 'en' => 'Evidence complete'],
        'problem' => ['ar' => 'المشكلة', 'en' => 'Problem'],
        'example_problem' => ['ar' => 'تشتت رحلة البحث', 'en' => 'A fragmented job search'],
        'my_role' => ['ar' => 'دوري', 'en' => 'My role'],
        'example_my_role' => ['ar' => 'تنفيذ من البداية', 'en' => 'Built from the ground up'],
        'outcome' => ['ar' => 'النتيجة', 'en' => 'Outcome'],
        'example_outcome' => ['ar' => 'نظام محلي عامل', 'en' => 'A working local system'],
        'principles_heading' => ['ar' => 'مشروعك ليس صورة نهائية فقط.', 'en' => 'Your project is more than a final image.'],
        'principle_why' => ['ar' => 'وثّق لماذا بدأ', 'en' => 'Document why it began'],
        'principle_role' => ['ar' => 'أثبت دورك الحقيقي', 'en' => 'Show your real role'],
        'principle_learning' => ['ar' => 'احفظ رحلة التعلم', 'en' => 'Preserve the learning journey'],
        'how_eyebrow' => ['ar' => 'كيف تعمل Ather؟', 'en' => 'How does Ather work?'],
        'how_heading' => ['ar' => 'من مشروع منسي إلى قصة مهنية واضحة', 'en' => 'From a forgotten project to a clear professional story'],
        'how_copy' => ['ar' => 'لا نطلب منك عرض النتيجة فقط. أثر يساعدك على تنظيم السياق، القرارات، دورك، وما خرجت به من كل تجربة.', 'en' => 'We don\'t just ask you to show the result. Ather helps you organize the context, decisions, your role, and what you took away from every experience.'],
        'step_one' => ['ar' => '1', 'en' => '1'],
        'step_one_heading' => ['ar' => 'ابنِ هويتك المهنية', 'en' => 'Build your professional identity'],
        'step_one_copy' => ['ar' => 'عرّف بنفسك ومجالك واتجاهك المهني، وابدأ بملف خاص لا يراه أحد قبل قرارك.', 'en' => 'Introduce yourself, your field, and your career direction. Start with a private portfolio that no one sees until you decide.'],
        'step_two' => ['ar' => '2', 'en' => '2'],
        'step_two_heading' => ['ar' => 'أضف مشاريعك وأدلتها', 'en' => 'Add your projects and evidence'],
        'step_two_copy' => ['ar' => 'سجّل المشكلة التي واجهتها، مسؤوليتك الشخصية، والنتيجة دون ادعاءات غير موثقة.', 'en' => 'Record the problem you faced, your personal responsibility, and the result, without unsupported claims.'],
        'step_three' => ['ar' => '3', 'en' => '3'],
        'step_three_heading' => ['ar' => 'انشر ما تختاره', 'en' => 'Publish what you choose'],
        'step_three_copy' => ['ar' => 'راجع المعاينة وتحكم بظهور مشاريعك وأدلتها ومعلومات التواصل بصورة مستقلة.', 'en' => 'Review the preview and independently control the visibility of your projects, evidence, and contact information.'],
        'evidence_eyebrow' => ['ar' => 'Evidence، لا ادعاءات', 'en' => 'Evidence, not claims'],
        'evidence_heading' => ['ar' => 'دع الزائر يفهم تفكيرك، لا أن يرى عنوان المشروع فقط', 'en' => 'Let visitors understand your thinking, beyond a project title'],
        'evidence_copy' => ['ar' => 'الملف القوي لا يقول «أنا أمتلك هذه المهارة» فقط؛ بل يربطها بمشكلة حقيقية، دور واضح، ونتيجة يمكن تفسيرها.', 'en' => 'A strong portfolio doesn\'t just say “I have this skill.” It connects the skill to a real problem, a clear role, and an outcome you can explain.'],
        'evidence_action' => ['ar' => 'لماذا هذا مهم؟', 'en' => 'Why does this matter?'],
        'evidence_problem' => ['ar' => 'ما الذي دفعك إلى بناء المشروع؟', 'en' => 'What led you to build the project?'],
        'personal_role' => ['ar' => 'الدور الشخصي', 'en' => 'Personal role'],
        'evidence_role' => ['ar' => 'ما الذي نفذته أنت فعلًا؟', 'en' => 'What did you actually implement yourself?'],
        'evidence_outcome' => ['ar' => 'ماذا خرج من التجربة؟ وماذا بقي للمستقبل؟', 'en' => 'What came out of the experience? What remains for the future?'],
        'values_eyebrow' => ['ar' => 'أثر ليست منصة عرض فقط', 'en' => 'Ather is more than a showcase'],
        'values_heading' => ['ar' => 'ملف ينمو معك ويحفظ ما تعلمته', 'en' => 'A portfolio that grows with you and preserves what you learn'],
        'values_copy' => ['ar' => 'مصممة للطلاب والخريجين وبدايات المسار المهني، لتقليل التشتت وبناء ثقة تستند إلى عمل حقيقي.', 'en' => 'Designed for students, graduates, and people starting their careers, to reduce fragmentation and build trust grounded in real work.'],
        'memory_heading' => ['ar' => 'ذاكرة مهنية', 'en' => 'Professional memory'],
        'memory_copy' => ['ar' => 'لا تنسَ بعد أشهر لماذا بنيت المشروع أو كيف اتخذت قراراتك.', 'en' => 'Months later, remember why you built a project and how you made your decisions.'],
        'ethical_heading' => ['ar' => 'تسويق أخلاقي لمهاراتك', 'en' => 'Present your skills ethically'],
        'ethical_copy' => ['ar' => 'اعرض قدراتك من خلال العمل والسياق بدل الكلمات العامة والمبالغة.', 'en' => 'Show your abilities through work and context, beyond broad claims and exaggeration.'],
        'growth_heading' => ['ar' => 'نمو مستمر', 'en' => 'Continuous growth'],
        'growth_copy' => ['ar' => 'ابدأ من وضعك الحالي، ثم طوّر ملفك ومشاريعك مع تطور مسارك.', 'en' => 'Start where you are, then develop your portfolio and projects as your career evolves.'],
        'privacy_eyebrow' => ['ar' => 'أنت تتحكم بما يظهر', 'en' => 'You control what is visible'],
        'privacy_heading' => ['ar' => 'خاص أولًا، والنشر قرارك', 'en' => 'Private first. Publishing is your decision.'],
        'privacy_copy' => ['ar' => 'حسابك وملفك ومشاريعك تبدأ خاصة. نشر المشروع لا يعني تلقائيًا نشر أدلته أو رقم هاتفك.', 'en' => 'Your account, portfolio, and projects start private. Publishing a project does not automatically publish its evidence or your phone number.'],
        'private_build' => ['ar' => 'الملف خاص أثناء البناء', 'en' => 'Private while you build'],
        'preview' => ['ar' => 'معاينة قبل النشر', 'en' => 'Preview before publishing'],
        'visibility' => ['ar' => 'تحكم مستقل بالمشروع والأدلة', 'en' => 'Independent project and evidence visibility'],
        'phone_private' => ['ar' => 'الهاتف خاص افتراضيًا', 'en' => 'Phone number private by default'],
        'final_heading' => ['ar' => 'كل مشروع ترك فيك أثرًا.', 'en' => 'Every project left an impact on you.'],
        'final_impact' => ['ar' => 'حان الوقت أن يراه الآخرون.', 'en' => 'It\'s time for others to see it.'],
        'final_copy' => ['ar' => 'ابدأ ملفك المهني الخاص، وثّق مشروعك الأول، ثم قرر بنفسك متى يصبح جاهزًا للنشر.', 'en' => 'Start your private professional portfolio, document your first project, and decide when it is ready to publish.'],
        'footer_brand' => ['ar' => 'Ather', 'en' => 'Ather'],
        'footer_privacy' => ['ar' => 'الخصوصية', 'en' => 'Privacy'],
        'footer_terms' => ['ar' => 'الشروط', 'en' => 'Terms'],
        'footer_security' => ['ar' => 'الأمان', 'en' => 'Security'],
        'footer_contact' => ['ar' => 'تواصل معنا', 'en' => 'Contact us'],
        'footer_tagline' => ['ar' => 'من الأردن، لمسار مهني أوضح', 'en' => 'From Jordan, for a clearer career journey'],
        'existing_sign_in' => ['ar' => 'تسجيل الدخول للحسابات الحالية', 'en' => 'Sign in to an existing account'],
        'availability' => ['ar' => 'التسجيل العام غير متاح بعد. تسجيل الدخول للحسابات الحالية فقط.', 'en' => 'Public registration is not available yet. Sign-in is for existing accounts only.'],
        'main_label' => ['ar' => 'أثر — هويتك المهنية وقصص مشاريعك', 'en' => 'Ather — your professional identity and project stories'],
        'nav_label' => ['ar' => 'التنقل الرئيسي', 'en' => 'Main navigation'],
        'example_label' => ['ar' => 'مثال توضيحي على ملف مشروع موثق في أثر', 'en' => 'Illustrative example of a documented project in Ather'],
        'menu_open' => ['ar' => 'فتح القائمة', 'en' => 'Open menu'],
        'menu_close' => ['ar' => 'إغلاق القائمة', 'en' => 'Close menu'],
        'theme' => ['ar' => 'المظهر الداكن', 'en' => 'Dark theme'],
        'skip' => ['ar' => 'انتقل إلى المحتوى', 'en' => 'Skip to content'],
        'language' => ['ar' => 'Read in English', 'en' => 'اقرأ بالعربية'],
        'title' => ['ar' => 'أثر | أظهر الأثر الذي صنعته', 'en' => 'Ather | Show the impact you made'],
        'description' => ['ar' => 'حوّل مشاريعك وتجاربك إلى قصة مهنية موثقة. أثر يحفظ دورك وقراراتك وأدلتك، والنشر قرارك.', 'en' => 'Turn your projects and experiences into a documented professional story. Preserve your role, decisions, and evidence. Publishing is your choice.'],
    ];

    return htmlspecialchars($catalog[$key][$locale], ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
